import { Recipe } from './types';

export const sampleRecipes: Recipe[] = [
  {
    id: '1',
    title: 'Greek Yogurt Protein Bowl',
    description:
      'A high-protein breakfast bowl with Greek yogurt, berries, and nuts. Perfect for GLP-1 users who need protein-rich, easy-to-digest meals.',
    image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400',
    nutrition: {
      protein: 25,
      calories: 320,
      carbs: 28,
      fat: 12,
    },
    isGlp1Friendly: true,
    glp1Notes: 'High protein, easy on stomach',
    prepTime: 5,
    cookTime: 0,
    servings: 1,
    ingredients: [
      { name: 'Greek yogurt (plain, 2%)', amount: '1 cup' },
      { name: 'Mixed berries', amount: '1/2 cup' },
      { name: 'Almonds (sliced)', amount: '2 tbsp' },
      { name: 'Chia seeds', amount: '1 tbsp' },
      { name: 'Honey (optional)', amount: '1 tsp' },
    ],
    instructions: [
      'Add Greek yogurt to a bowl.',
      'Top with mixed berries.',
      'Sprinkle sliced almonds and chia seeds.',
      'Drizzle with honey if desired.',
    ],
    category: 'breakfast',
    tags: ['high-protein', 'quick', 'no-cook'],
  },
  {
    id: '2',
    title: 'Lemon Herb Salmon',
    description:
      'Light and flavorful baked salmon with fresh herbs. Rich in omega-3s and protein, gentle on the digestive system.',
    image: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=400',
    nutrition: {
      protein: 35,
      calories: 380,
      carbs: 4,
      fat: 22,
    },
    isGlp1Friendly: true,
    glp1Notes: 'Omega-3 rich, low nausea risk',
    prepTime: 10,
    cookTime: 15,
    servings: 2,
    ingredients: [
      { name: 'Salmon fillets', amount: '2 (6 oz each)' },
      { name: 'Lemon', amount: '1, sliced' },
      { name: 'Fresh dill', amount: '2 tbsp, chopped' },
      { name: 'Garlic', amount: '2 cloves, minced' },
      { name: 'Olive oil', amount: '1 tbsp' },
      { name: 'Salt and pepper', amount: 'to taste' },
    ],
    instructions: [
      'Preheat oven to 400°F (200°C).',
      'Place salmon on a lined baking sheet.',
      'Drizzle with olive oil and season with salt, pepper, and garlic.',
      'Top with lemon slices and fresh dill.',
      'Bake for 12-15 minutes until salmon flakes easily.',
    ],
    category: 'dinner',
    tags: ['high-protein', 'omega-3', 'low-carb'],
  },
  {
    id: '3',
    title: 'Turkey Lettuce Wraps',
    description:
      'Light and satisfying lettuce wraps with seasoned ground turkey. Small portions perfect for reduced appetite.',
    image: 'https://images.unsplash.com/photo-1529059997568-3d847b1154f0?w=400',
    nutrition: {
      protein: 28,
      calories: 260,
      carbs: 8,
      fat: 14,
    },
    isGlp1Friendly: true,
    glp1Notes: 'Small portions, easy to digest',
    prepTime: 10,
    cookTime: 10,
    servings: 2,
    ingredients: [
      { name: 'Ground turkey (lean)', amount: '1/2 lb' },
      { name: 'Butter lettuce leaves', amount: '8 large' },
      { name: 'Soy sauce (low sodium)', amount: '2 tbsp' },
      { name: 'Ginger', amount: '1 tsp, minced' },
      { name: 'Green onions', amount: '2, sliced' },
      { name: 'Sesame oil', amount: '1 tsp' },
    ],
    instructions: [
      'Heat sesame oil in a pan over medium-high heat.',
      'Add ground turkey and cook until browned.',
      'Add ginger and soy sauce, stir to combine.',
      'Cook for 2-3 more minutes.',
      'Spoon mixture into lettuce cups and top with green onions.',
    ],
    category: 'lunch',
    tags: ['high-protein', 'low-carb', 'quick'],
  },
  {
    id: '4',
    title: 'Protein Smoothie',
    description:
      'A creamy, protein-packed smoothie that is gentle on the stomach. Great for days when solid food feels challenging.',
    image: 'https://images.unsplash.com/photo-1553530666-ba11a7da3888?w=400',
    nutrition: {
      protein: 30,
      calories: 280,
      carbs: 24,
      fat: 8,
    },
    isGlp1Friendly: true,
    glp1Notes: 'Easy to consume, hydrating',
    prepTime: 5,
    cookTime: 0,
    servings: 1,
    ingredients: [
      { name: 'Protein powder (vanilla)', amount: '1 scoop' },
      { name: 'Almond milk (unsweetened)', amount: '1 cup' },
      { name: 'Banana (frozen)', amount: '1/2' },
      { name: 'Peanut butter', amount: '1 tbsp' },
      { name: 'Ice cubes', amount: '1/2 cup' },
    ],
    instructions: [
      'Add almond milk to blender.',
      'Add protein powder, frozen banana, and peanut butter.',
      'Add ice cubes.',
      'Blend until smooth, about 30-60 seconds.',
      'Pour into glass and enjoy immediately.',
    ],
    category: 'smoothie',
    tags: ['high-protein', 'quick', 'no-cook'],
  },
  {
    id: '5',
    title: 'Egg White Veggie Scramble',
    description:
      'A light, protein-rich scramble with colorful vegetables. Low fat and easy to digest for sensitive stomachs.',
    image: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=400',
    nutrition: {
      protein: 22,
      calories: 180,
      carbs: 8,
      fat: 6,
    },
    isGlp1Friendly: true,
    glp1Notes: 'Low fat, high protein',
    prepTime: 5,
    cookTime: 8,
    servings: 1,
    ingredients: [
      { name: 'Egg whites', amount: '4 large' },
      { name: 'Spinach', amount: '1 cup' },
      { name: 'Bell pepper (diced)', amount: '1/4 cup' },
      { name: 'Cherry tomatoes', amount: '4, halved' },
      { name: 'Feta cheese', amount: '1 tbsp, crumbled' },
      { name: 'Cooking spray', amount: 'as needed' },
    ],
    instructions: [
      'Spray a non-stick pan with cooking spray and heat over medium.',
      'Add bell pepper and cook for 2 minutes.',
      'Add spinach and cook until wilted.',
      'Pour in egg whites and gently scramble.',
      'Add tomatoes in the last minute.',
      'Top with feta cheese and serve.',
    ],
    category: 'breakfast',
    tags: ['high-protein', 'low-fat', 'quick'],
  },
  {
    id: '6',
    title: 'Chicken Bone Broth Soup',
    description:
      'A soothing, nutrient-dense soup perfect for days when appetite is low. Hydrating and easy on the stomach.',
    image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400',
    nutrition: {
      protein: 18,
      calories: 150,
      carbs: 6,
      fat: 4,
    },
    isGlp1Friendly: true,
    glp1Notes: 'Hydrating, gentle on stomach',
    prepTime: 10,
    cookTime: 20,
    servings: 2,
    ingredients: [
      { name: 'Chicken bone broth', amount: '4 cups' },
      { name: 'Shredded chicken breast', amount: '1 cup' },
      { name: 'Carrots (sliced)', amount: '1/2 cup' },
      { name: 'Celery (sliced)', amount: '1/2 cup' },
      { name: 'Fresh thyme', amount: '2 sprigs' },
      { name: 'Salt and pepper', amount: 'to taste' },
    ],
    instructions: [
      'Bring bone broth to a simmer in a pot.',
      'Add carrots and celery, cook for 10 minutes.',
      'Add shredded chicken and thyme.',
      'Simmer for another 10 minutes.',
      'Season with salt and pepper to taste.',
      'Remove thyme sprigs before serving.',
    ],
    category: 'lunch',
    tags: ['high-protein', 'hydrating', 'comfort-food'],
  },
  {
    id: '7',
    title: 'Cottage Cheese Snack Bowl',
    description:
      'A quick, protein-packed snack with cottage cheese and cucumber. Refreshing and easy to eat in small amounts.',
    image: 'https://images.unsplash.com/photo-1452195100486-9cc805987862?w=400',
    nutrition: {
      protein: 20,
      calories: 160,
      carbs: 10,
      fat: 4,
    },
    isGlp1Friendly: true,
    glp1Notes: 'Light snack, high protein',
    prepTime: 3,
    cookTime: 0,
    servings: 1,
    ingredients: [
      { name: 'Cottage cheese (low-fat)', amount: '1 cup' },
      { name: 'Cucumber (diced)', amount: '1/2 cup' },
      { name: 'Cherry tomatoes', amount: '4, halved' },
      { name: 'Everything bagel seasoning', amount: '1/2 tsp' },
      { name: 'Fresh dill', amount: '1 tsp, chopped' },
    ],
    instructions: [
      'Add cottage cheese to a bowl.',
      'Top with diced cucumber and cherry tomatoes.',
      'Sprinkle with everything bagel seasoning.',
      'Garnish with fresh dill.',
    ],
    category: 'snack',
    tags: ['high-protein', 'quick', 'no-cook'],
  },
  {
    id: '8',
    title: 'Baked Cod with Vegetables',
    description:
      'Mild white fish baked with roasted vegetables. Very gentle on the stomach with excellent protein content.',
    image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=400',
    nutrition: {
      protein: 32,
      calories: 290,
      carbs: 12,
      fat: 8,
    },
    isGlp1Friendly: true,
    glp1Notes: 'Mild flavor, very easy to digest',
    prepTime: 10,
    cookTime: 20,
    servings: 2,
    ingredients: [
      { name: 'Cod fillets', amount: '2 (6 oz each)' },
      { name: 'Zucchini (sliced)', amount: '1 medium' },
      { name: 'Cherry tomatoes', amount: '1 cup' },
      { name: 'Olive oil', amount: '1 tbsp' },
      { name: 'Italian herbs', amount: '1 tsp' },
      { name: 'Lemon juice', amount: '2 tbsp' },
    ],
    instructions: [
      'Preheat oven to 400°F (200°C).',
      'Arrange cod and vegetables on a baking sheet.',
      'Drizzle with olive oil and lemon juice.',
      'Season with Italian herbs, salt, and pepper.',
      'Bake for 18-20 minutes until fish is flaky.',
    ],
    category: 'dinner',
    tags: ['high-protein', 'low-fat', 'one-pan'],
  },
  {
    id: '9',
    title: 'Loaded Bacon Cheeseburger',
    description:
      'A juicy, indulgent burger stacked with crispy bacon, melted cheddar, and all the fixings. Sometimes you just need comfort food.',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400',
    nutrition: {
      protein: 42,
      calories: 850,
      carbs: 45,
      fat: 52,
    },
    isGlp1Friendly: false,
    glp1Notes: undefined,
    prepTime: 15,
    cookTime: 15,
    servings: 2,
    ingredients: [
      { name: 'Ground beef (80/20)', amount: '1 lb' },
      { name: 'Bacon strips', amount: '6 slices' },
      { name: 'Cheddar cheese', amount: '4 slices' },
      { name: 'Brioche buns', amount: '2 large' },
      { name: 'Lettuce, tomato, onion', amount: 'as desired' },
      { name: 'Mayo and ketchup', amount: 'to taste' },
    ],
    instructions: [
      'Form beef into 2 large patties, season generously with salt and pepper.',
      'Cook bacon in a skillet until crispy, set aside.',
      'Grill or pan-fry patties for 4-5 minutes per side.',
      'Add cheese in the last minute to melt.',
      'Toast buns lightly on the grill.',
      'Assemble with mayo, lettuce, patty, cheese, bacon, tomato, onion, and ketchup.',
    ],
    category: 'dinner',
    tags: ['indulgent', 'comfort-food', 'high-protein'],
  },
  {
    id: '10',
    title: 'Deep Dish Mac and Cheese',
    description:
      'Ultra-creamy, four-cheese mac and cheese with a crispy breadcrumb topping. Pure cheesy comfort in every bite.',
    image: 'https://images.unsplash.com/photo-1543339494-b4cd4f7ba686?w=400',
    nutrition: {
      protein: 28,
      calories: 720,
      carbs: 58,
      fat: 42,
    },
    isGlp1Friendly: false,
    glp1Notes: undefined,
    prepTime: 15,
    cookTime: 30,
    servings: 4,
    ingredients: [
      { name: 'Elbow macaroni', amount: '1 lb' },
      { name: 'Sharp cheddar', amount: '2 cups, shredded' },
      { name: 'Gruyère cheese', amount: '1 cup, shredded' },
      { name: 'Cream cheese', amount: '4 oz' },
      { name: 'Heavy cream', amount: '1 cup' },
      { name: 'Butter', amount: '4 tbsp' },
      { name: 'Panko breadcrumbs', amount: '1 cup' },
    ],
    instructions: [
      'Cook pasta according to package directions, drain.',
      'Melt butter in a large pot, whisk in flour to make a roux.',
      'Slowly add heavy cream, stirring constantly.',
      'Add cream cheese and stir until melted.',
      'Add cheddar and gruyère, stir until smooth.',
      'Combine with pasta, transfer to baking dish.',
      'Top with buttered panko and bake at 375°F for 20 minutes until golden.',
    ],
    category: 'dinner',
    tags: ['indulgent', 'comfort-food', 'cheesy'],
  },
  {
    id: '11',
    title: 'Crispy Fried Chicken',
    description:
      'Golden, crunchy fried chicken with a perfectly seasoned buttermilk coating. Crispy outside, juicy inside.',
    image: 'https://images.unsplash.com/photo-1626645738196-c2a7c87a8f58?w=400',
    nutrition: {
      protein: 38,
      calories: 680,
      carbs: 32,
      fat: 44,
    },
    isGlp1Friendly: false,
    glp1Notes: undefined,
    prepTime: 30,
    cookTime: 20,
    servings: 4,
    ingredients: [
      { name: 'Chicken pieces (thighs & drumsticks)', amount: '3 lbs' },
      { name: 'Buttermilk', amount: '2 cups' },
      { name: 'All-purpose flour', amount: '2 cups' },
      { name: 'Paprika', amount: '2 tsp' },
      { name: 'Garlic powder', amount: '1 tsp' },
      { name: 'Cayenne pepper', amount: '1/2 tsp' },
      { name: 'Vegetable oil', amount: 'for frying' },
    ],
    instructions: [
      'Marinate chicken in buttermilk for at least 2 hours (overnight is best).',
      'Mix flour with paprika, garlic powder, cayenne, salt, and pepper.',
      'Heat oil to 350°F in a deep pot or Dutch oven.',
      'Dredge chicken pieces in seasoned flour, shaking off excess.',
      'Fry in batches for 12-15 minutes until golden and cooked through.',
      'Rest on a wire rack for 5 minutes before serving.',
    ],
    category: 'dinner',
    tags: ['indulgent', 'crispy', 'comfort-food'],
  },
  {
    id: '12',
    title: 'Chocolate Lava Cake',
    description:
      'Decadent individual chocolate cakes with a molten, gooey center. The ultimate chocolate indulgence.',
    image: 'https://images.unsplash.com/photo-1624353365286-3f8d62daad51?w=400',
    nutrition: {
      protein: 8,
      calories: 480,
      carbs: 42,
      fat: 32,
    },
    isGlp1Friendly: false,
    glp1Notes: undefined,
    prepTime: 15,
    cookTime: 12,
    servings: 4,
    ingredients: [
      { name: 'Dark chocolate (70%)', amount: '6 oz' },
      { name: 'Butter', amount: '1/2 cup' },
      { name: 'Eggs', amount: '2 whole + 2 yolks' },
      { name: 'Sugar', amount: '1/4 cup' },
      { name: 'All-purpose flour', amount: '2 tbsp' },
      { name: 'Vanilla extract', amount: '1 tsp' },
      { name: 'Powdered sugar', amount: 'for dusting' },
    ],
    instructions: [
      'Preheat oven to 425°F. Butter and flour 4 ramekins.',
      'Melt chocolate and butter together, let cool slightly.',
      'Whisk eggs, yolks, sugar, and vanilla until thick.',
      'Fold chocolate mixture into eggs, then fold in flour.',
      'Divide batter among ramekins.',
      'Bake for 12-14 minutes until edges are firm but center is soft.',
      'Let cool 1 minute, invert onto plates, dust with powdered sugar.',
    ],
    category: 'snack',
    tags: ['indulgent', 'chocolate', 'dessert'],
  },
];

export function getRecipeById(id: string): Recipe | undefined {
  return sampleRecipes.find((recipe) => recipe.id === id);
}

export function getRecipesByCategory(category: Recipe['category']): Recipe[] {
  return sampleRecipes.filter((recipe) => recipe.category === category);
}
